# Aula 01 - Primeiro Contato

## O que é TensorFlow?

O TensorFlow é um framework de código aberto criado pelo Google para o desenvolvimento e execução de modelos de **machine learning** e **deep learning**.

Ele permite criar e treinar redes neurais com grande flexibilidade e eficiência, utilizando **tensores** (estruturas de dados multidimensionais) como base para os cálculos.

- Foi desenvolvido pelo Google Brain Team;
- Suporta tanto CPU quanto GPU (e até TPU - é um processador otimizado especificamente para operações de inteligência artificial e aprendizado de máquina);
- Permite criar modelos usando tanto alto nível (Keras) quanto baixo nível (operações matemáticas customizadas).

## O que é Keras?

O Keras é uma **API de alto nível** para construção e treinamento de modelos de deep learning. Foi projetada para ser simples, intuitiva e modular, o que a torna ideal para iniciantes e também poderosa o suficiente para especialistas.

Originalmente, o Keras podia ser usado com diversos backends (Theano, CNTK, TensorFlow). Mas desde 2017, ele foi integrado oficialmente ao TensorFlow e passou a ser o frontend oficial do framework (TensorFlow).

## Usando o Keras

A partir do TensorFlow 2.0, o Keras foi completamente integrado e passou a ser acessado por meio do módulo:

```python
import tensorflow.keras as keras
```

Ou ainda:

```python
import tensorflow as keras
```

## Em Resumo:

| Termo | O que é | Papel Principal |
|---|---|---|
|TensorFlow|Framework de ML/DL de baixo a alto ní­vel|Motor de cálculo (backend)|
|Keras|API de alto nível para construção de modelos|Interface amigável sobre o TensorFlow|



## Classificação de Flores
**Características das Flores**

1. Comprimento e largura de **pétalas**
1. Comprimento e larguara de **sépelas**

**Classificação**

Verificar se a flor **iris** é 

- Versicolor
- Setosa
- Virginica

In [1]:
# Instalar os pacotes necessários
# !pip install --upgrade pip
# !pip install tensorflow
# !pip install pydot

In [2]:
# Importar o tensorflow
import tensorflow as tf
print(tf.__version__) # 2.19.0

# Importar o Keras
import tensorflow.keras as keras

# Outros pacotes
import pydot

2.19.0


In [3]:
# O Sequential une várias camadas do modelo
# Camadas são um conjunto de neurônios para compor uma rede neural completa
# A camada Dense executa todos os cálculos do modelo (perceptron)

# Parâmetros
# units = qtd de neurônios
# keras.Input =  qtd de entradas do modelo (ex: largura e comprimento das pétalas)

modelo = keras.Sequential([ 
    keras.Input(shape=[2]),
    keras.layers.Dense( units=1, name='Neurônio')
])

In [4]:
# Algumas informações do modelo em texto
# 3 parâmetros porque são dois pesos mais o bias

modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Neurônio (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# Retorna uma lista contendo as camadas do modelo criado
# Neste caso, retorna somente a camada Dense chamada Neurônio
modelo.layers

[<Dense name=Neurônio, built=True>]

In [6]:
# Coleta os pesos e viéses da camada enviada como objeto e os retorna como lista
modelo.layers[0].get_weights()

# modelo.layers[0].get_weights()[0] mostra somente os pesos
# modelo.layers[0].get_weights()[1] mostra somente o bias

[array([[-0.00107455],
        [ 0.0559305 ]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
# Cria variáveis para pesos e bias
# pesos recebe modelo.layers[0].get_weights()[0]
# bias recebe modelo.layers[0].get_weights()[1]

pesos, bias = modelo.layers[0].get_weights()

In [8]:
# Pesos

# mostra o tamanho
print(pesos.shape)

# mostra o conteúdo
pesos

(2, 1)


array([[-0.00107455],
       [ 0.0559305 ]], dtype=float32)

In [9]:
# Bias

# mostra o tamanho
print(bias.shape)

# mostra o conteúdo
bias

# Neste caso, o bias é 0

(1,)


array([0.], dtype=float32)

## Iniciar o modelo com parâmetros

In [10]:

modelo = keras.Sequential([ 
    keras.Input(shape=[2]),
    keras.layers.Dense(
        units=1,
        name='Neurônio',
        kernel_initializer=keras.initializers.RandomNormal(), # define os pesos
        bias_initializer=keras.initializers.Ones() # define o bias
    )
])

In [11]:
# Verificação dos pesos e bias
modelo.layers[0].get_weights()

[array([[0.12909387],
        [0.03539822]], dtype=float32),
 array([1.], dtype=float32)]